### ISSUE TITLE
Vue Composition API Implementation

### ISSUE THREAD

**Issue by AbidemiT** [slightlynerd/startupgraveyard.africa#13]
**I feel it will be nice to have the latest vue ecosystem implementation to help developers pick up new projects with ease.**

**I will be setting up each vue component in composition API format; its flexibility enables more powerful patterns for organizing and reusing logic.**

**Comment by AbidemiT** [comment]
@slightlynerd

**Comment by KelvinGoboZap** [comment]
@AbidemiT Components already use composition API where necessary. I'll be closing this issue as changes to the current structure are not needed. I've opened some other issues where contribution is needed so please take a look at those and assign to yourself if you find something you'll like to work on.

**Comment by slightlynerd** [comment]
@AbidemiT Components already use composition API where necessary. I'll be closing this issue as changes to the current structure are not needed. I've opened some other issues where contribution is needed so please take a look at those and assign to yourself if you find something you'll like to work on.

**Comment by slightlynerd** [comment]
@AbidemiT Components already use composition API where necessary. I'll be closing this issue as changes to the current structure are not needed. I've opened some other issues where contribution is needed so please take a look at those and assign to yourself if you find something you'll like to work on.

**Comment by slightlynerd** [comment]
@AbidemiT I know that but at this time, I'm not looking to change this. It will be done at some point, just not now.
