### ISSUE TITLE
Make footer fixed to the bottom of the page

### ISSUE THREAD

**Issue by slightlynerd** [slightlynerd/startupgraveyard.africa#23]
## This issue has a bounty of $5. Please read the [contribution guide](https://github.com/slightlynerd/startupgraveyard.africa/blob/main/CONTRIBUTION.md) for instructions and terms of bounties.

**Is your feature request related to a problem? Please describe.**
The page footer is not fixed to the bottom of the page.
<img width="1015" alt="Screenshot 2024-04-12 at 19 37 43" src="https://github.com/slightlynerd/startupgraveyard.africa/assets/19628361/6cf74498-7b6b-4eaa-b6f9-5030cceef402">
There's also a workaround on the blog article page `/pages/blog/[id].vue` to fix the footer to the bottom on resize of the page (see the **TODO** comment the `onMounted()` hook.

**Describe the solution you'd like**
Footer should be fixed to the bottom of the page using HTML and CSS so there's no need for JS workaround and the footer is always fixed to the bottom.

**Additional context**

**Comment by peoray** [comment]
@slightlynerd great initiative 👏🏽 

is this still an issue? the recent post section makes it look like it is already at the bottom of the page, not sure though

**Comment by slightlynerd** [comment]
@peoray Thank you 🙏🏽

It's still an open issue. As you pointed out, it's been fixed on the landing page. 
But on the blog article page, there's a workaround used to fix the footer to the bottom. I added details about it in the original issue. It'll be better if the footer is fixed to the bottom of the page without the current workaround which is quite hacky.

**Comment by peoray** [comment]
@slightlynerd can you share a screenshot? still looks good from my end
![Uploading Screenshot 2024-04-30 at 1.18.29 PM.png…]()

**Comment by slightlynerd** [comment]
@peoray The footer is fixed to the bottom, but the solution is hacky 😅. You can remove the style attribute at the beginning of the file to see the issue:
<img width="812" alt="Screenshot 2024-04-30 at 13 22 53" src="https://github.com/slightlynerd/startupgraveyard.africa/assets/19628361/f7c0bb65-bccb-40c2-9afd-03834e614df1">

I'll like to have a cleaner, less hacky solution.

**Comment by peoray** [comment]
@slightlynerd got that, already left an edit to my comment :)

picking this issue up then
