### ISSUE TITLE
Add recent blog posts sidebar to the blog article page

### ISSUE THREAD

**Issue by slightlynerd** [slightlynerd/startupgraveyard.africa#24]
## This issue has a bounty of $5. Please read the [contribution guide](https://github.com/slightlynerd/startupgraveyard.africa/blob/main/CONTRIBUTION.md) for instructions and terms of bounties.

**Is your feature request related to a problem? Please describe.**
Add a section for recent posts on the blog article page
<img width="457" alt="Screenshot 2024-04-23 at 03 45 15" src="https://github.com/slightlynerd/startupgraveyard.africa/assets/19628361/c7d1a3e8-a0b6-4acc-8790-a63b209eaf83">

**Describe the solution you'd like**
There should be a section that loads the 3 most recent blog articles from firebase and displays it in the space beside the blog article.
<img width="1439" alt="Screenshot 2024-04-23 at 03 45 56" src="https://github.com/slightlynerd/startupgraveyard.africa/assets/19628361/ef4dcc99-bc79-4519-b972-87ae883ccdd8">

On mobile, it should be collapsed into a column and come under the blog article.

**Comment by tsomic** [comment]
@slightlynerd did you have something like this in mind?

![image](https://github.com/slightlynerd/startupgraveyard.africa/assets/60610467/80c2b1e6-d884-41e6-935d-76f965a39a3a)

**Comment by slightlynerd** [comment]
@tsomic Yes, that's what I had in mind. Can you make the recent posts `position: sticky` on desktop view? So it's always in view even as a user scrolls down the article. But when the row is collapsed on smaller screens, position is reset back to `relative` or `auto`.

**Comment by tsomic** [comment]
This doesn't feel super natural to me to use, as I cannot access the latter blog posts unless I scroll to the bottom of the page. What would you suggest?

![image](https://github.com/slightlynerd/startupgraveyard.africa/assets/60610467/b6ea6326-cc0d-4e3c-8783-8b37d9568ed9)

![image](https://github.com/slightlynerd/startupgraveyard.africa/assets/60610467/9b3b5bd0-a6b5-4122-a8fc-b84bf2886f49)

**Comment by slightlynerd** [comment]
@tsomic In this case, revert it back to previous solution.
