### ISSUE TITLE
Implement search on the blog page

### ISSUE THREAD

**Issue by slightlynerd** [slightlynerd/startupgraveyard.africa#25]
## This issue has a bounty of $5. Please read the [contribution guide](https://github.com/slightlynerd/startupgraveyard.africa/blob/main/CONTRIBUTION.md) for instructions and terms of bounties.

**Is your feature request related to a problem? Please describe.**
There's no way to search through blog articles.

**Describe the solution you'd like**
Add a search input field to the blog page (https://startupgraveyard.africa/blog) and implement the search functionality.
- search input should be above the "Recent Posts" text
- it should be centered and 50% width on desktop, 80% on tablet, and 100% on mobile.
- search lookup is not triggered until the user enters at least 2 characters
- search results should show the top 4 results in descending order, from the most recent to the oldest

**Comment by darkfuva** [comment]
Intrested
