### ISSUE TITLE
I should be able to search/filter by countries 

### ISSUE THREAD

**Issue by happi2206** [slightlynerd/startupgraveyard.africa#5]
e.g I want to see a list of all the startups that failed in Nigeria without having to scroll manually to find all of them

**Comment by seanmavley** [comment]
Was about to say this. Perhaps a PR would be in order

**Comment by slightlynerd** [comment]
@happi2206 That's a good point. I'll add this once I get the chance. I don't have a timeline for when but I'll look to add it.

@seanmavley The project is open to contributions so if you could send a PR, that would be great.

**Comment by slightlynerd** [comment]
@seanmavley The project is open to contributions so if you could send a PR, that would be great. Let me know if this is something that you would be interested in.

**Comment by happi2206** [comment]
@slightlynerd assign this to me
